export const VOWELS = [
    "अ",
    "आ",
    "इ",
    "ई",
    "उ",
    "ऊ",
    "ऋ",
    "ॠ",
    "ऌ",
    "ॡ",
    "ए",
    "ऐ",
    "ओ",
    "औ",
    "अं",
    "अः",
];
export const CONSONANTS = [
    "क",
    "ख",
    "ग",
    "घ",
    "ङ",
    "च",
    "छ",
    "ज",
    "झ",
    "ञ",
    "ट",
    "ठ",
    "ड",
    "ढ",
    "ण",
    "त",
    "थ",
    "द",
    "ध",
    "न",
    "प",
    "फ",
    "ब",
    "भ",
    "म",
    "य",
    "र",
    "ल",
    "व",
    "श",
    "ष",
    "स",
    "ह",
    "क्ष",
    "त्र",
    "ज्ञ",
];
export const MATRAS = [
    "ा",
    "ि",
    "ी",
    "ु",
    "ू",
    "ृ",
    "े",
    "ै",
    "ो",
    "ौ",
    "ं",
    "ः",
];
export const SPECIAL_GURUS = ["ॐ", "श्री"];
export const GANAS = {
    ISS: "Ya (य)",
    SSS: "Ma (म)",
    SSI: "Ta (त)",
    SIS: "Ra (र)",
    ISI: "Ja (ज)",
    SII: "Bha (भ)",
    III: "Na (न)",
    IIS: "Sa (स)",
};
export const CHHANDAS = {
    भुजङ्गप्रयात: ["ISS", "ISS", "ISS", "ISS"],
    शार्दूलविक्रीडित: ["SSS", "IIS", "ISI", "IIS", "SSI", "SSI", "S"],
    तोटक: ["IIS", "IIS", "IIS", "IIS"],
    मन्दाक्रान्ता: ["SSS", "SII", "III", "SSI", "SSI", "S", "S"],
    इन्द्रवज्र: ["SSI", "SSI", "ISI", "SS"],
    उपेन्द्रवज्र: ["ISI", "SSI", "ISI", "SS"],
    वंशस्थ: ["ISI", "SSI", "ISI", "SIS"],
    इन्द्रवंश: ["SSI", "SSI", "ISI", "SIS"],
    वसन्ततिलका: ["SSI", "SII", "ISI", "ISI", "SS"],
    मालिनी: ["III", "III", "SSS", "ISS", "ISS"],
    शिखरिणी: ["ISS", "SSS", "III", "IIS", "SII", "I", "S"],
    स्रग्विणी: ["SIS", "SIS", "SIS", "SIS"],
    स्रग्धरा: ["SSS", "SIS", "SII", "III", "ISS", "ISS", "ISS"],
    पृथ्वी: [
        "III",
        "III",
        "SSS",
        "ISS",
        "ISS",
        "III",
        "III",
        "SSS",
        "ISS",
        "ISS",
    ],
    द्रुतविलम्बित: ["III", "SII", "SII", "SIS"],
    पञ्चचामर: ["ISI", "SIS", "ISI", "SIS", "ISI", "S"],
    हरिणी: ["III", "IIS", "SSS", "SIS", "IIS", "IS"],
    श्रवणाभरणम्: ["III", "ISI", "ISI", "ISI", "ISI", "ISI", "ISI", "IS"],
    // Special meters with their own rules
    अनुष्टुप्: [], // Governed by positional rules, not gana sequence
    मात्रिक१४: [], // 14-matra meter
    आर्या: [], // Arya meter – special matra rules
};
/** Human-readable descriptions for each meter */
export const CHHANDAS_INFO = {
    भुजङ्गप्रयात: {
        syllablesPerLine: 12,
        classification: "Vṛtta",
        description: "Four Ya-ganas (ISS×4). 12 syllables per pada.",
    },
    शार्दूलविक्रीडित: {
        syllablesPerLine: 19,
        classification: "Vṛtta",
        description: "19-syllable meter. Used in majestic compositions.",
    },
    तोटक: {
        syllablesPerLine: 12,
        classification: "Vṛtta",
        description: "Four Sa-ganas (IIS×4). Light, flowing rhythm.",
    },
    मन्दाक्रान्ता: {
        syllablesPerLine: 17,
        classification: "Vṛtta",
        description: "17-syllable meter associated with Meghaduta.",
    },
    इन्द्रवज्र: {
        syllablesPerLine: 11,
        classification: "Vṛtta",
        description: "SSI SSI ISI SS – noble, dignified meter.",
    },
    उपेन्द्रवज्र: {
        syllablesPerLine: 11,
        classification: "Vṛtta",
        description: "ISI SSI ISI SS – lighter variant of Indravajra.",
    },
    वंशस्थ: {
        syllablesPerLine: 12,
        classification: "Vṛtta",
        description: "ISI SSI ISI SIS – used for flowing narratives.",
    },
    इन्द्रवंश: {
        syllablesPerLine: 12,
        classification: "Vṛtta",
        description: "SSI SSI ISI SIS – heavier variant of Vamsastha.",
    },
    वसन्ततिलका: {
        syllablesPerLine: 14,
        classification: "Vṛtta",
        description: "14-syllable meter. Popular in Nepali classical poetry.",
    },
    मालिनी: {
        syllablesPerLine: 15,
        classification: "Vṛtta",
        description: "III III SSS ISS ISS – 15 syllables, delicate cadence.",
    },
    शिखरिणी: {
        syllablesPerLine: 17,
        classification: "Vṛtta",
        description: "17-syllable meter with intricate rhythm.",
    },
    स्रग्विणी: {
        syllablesPerLine: 12,
        classification: "Vṛtta",
        description: "Four Ra-ganas (SIS×4). Melodic, garland-like flow.",
    },
    स्रग्धरा: {
        syllablesPerLine: 21,
        classification: "Vṛtta",
        description: "21-syllable meter – one of the longest classical Vṛtta meters.",
    },
    पृथ्वी: {
        syllablesPerLine: 17,
        classification: "Vṛtta",
        description: "17-syllable Prithvi meter with a distinctive break.",
    },
    द्रुतविलम्बित: {
        syllablesPerLine: 12,
        classification: "Vṛtta",
        description: "III SII SII SIS – swift, running rhythm.",
    },
    पञ्चचामर: {
        syllablesPerLine: 16,
        classification: "Vṛtta",
        description: "Alternating ISI/SIS pattern. 16 syllables.",
    },
    हरिणी: {
        syllablesPerLine: 17,
        classification: "Vṛtta",
        description: "III IIS SSS SIS IIS IS – graceful, deer-like movement.",
    },
    श्रवणाभरणम्: {
        syllablesPerLine: 21,
        classification: "Vṛtta",
        description: "21-syllable meter with repeated Ja-gana patterns.",
    },
    अनुष्टुप्: {
        syllablesPerLine: 8,
        classification: "Vṛtta",
        description: "8 syllables per pada, 4 padas. The most common Sanskrit/Nepali epic meter (Shloka). Identified by positional rules, not gana sequence.",
    },
    मात्रिक१४: {
        syllablesPerLine: 14,
        classification: "Mātrā-vṛtta",
        description: "14-matra meter. Counted by mora (matra) weight.",
    },
    आर्या: {
        syllablesPerLine: 0,
        classification: "Mātrā-vṛtta",
        description: "Arya meter. Matra-based with special rules for each pada.",
    },
};
//# sourceMappingURL=constant.js.map